// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkszvkszjvacqqwhyqab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrc3p2a3N6anZhY3Fxd2h5cWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTgwNDgsImV4cCI6MjA1ODMzNDA0OH0.AoPfoi9T_tO135xVJHX-xhEbE858b7o4h2p0-F2pqNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);